events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    gzip            on;
    gzip_types      text/css application/javascript application/json;
    gzip_min_length 2048;

    upstream jira_backend {
        server app:8080;
    }

    server {
        listen 80;
        server_name localhost;

        # Корень для статики – если нужно
        root /opt/jirarush/resources;
        index index.html;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Обработка статики
        location /static/ {
            expires 30d;
            access_log off;
        }

        location /robots.txt {
            access_log off;
        }

        # Прокси на приложение
        location ~ (/$|/view/|/ui/|/oauth2/) {
            proxy_pass http://jira_backend;
            proxy_connect_timeout 30s;
        }

        location ~ (/api/|/doc|/swagger-ui/|/v3/api-docs/) {
            proxy_pass http://jira_backend;
            proxy_connect_timeout 150s;
        }

        # Для всего остального – 404 или перенаправление
        location / {
            try_files $uri /view/404.html = 404;
        }
    }
}